import NSPCore
import NSPDesignSystem
import SwiftUI

/// docs/07 §4's Overview tab: duration, availability, processing mode, and
/// lifecycle state, plus the real executive-summary `Insight` once
/// processing has produced one, and the meeting's attendees (People
/// feature). Chapters still aren't generated by anything this pass — shown
/// as explicit absence, not blank space that looks broken.
struct OverviewTab: View {
    let meeting: Meeting
    let environment: AppEnvironment

    @State private var executiveSummary: Insight?
    @State private var attendees: [Person] = []
    @State private var isEditingAttendees = false
    @State private var linkedProjects: [Project] = []
    @State private var isEditingProject = false
    @State private var isConfirmingDelete = false
    @State private var deleteError: String?

    private var durationLabel: String {
        guard meeting.canonicalDuration.sampleCount > 0 else { return "—" }
        let totalSeconds = Int(meeting.canonicalDuration.seconds)
        return String(format: "%d:%02d:%02d", totalSeconds / 3600, (totalSeconds % 3600) / 60, totalSeconds % 60)
    }

    private var availabilityLabel: String {
        switch meeting.availability {
        case .complete: return "Complete"
        case .partial(let missing): return "Partial — \(missing.count) segment\(missing.count == 1 ? "" : "s") missing"
        case .recoverable: return "Recoverable"
        case .failed: return "Failed"
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: NSPSpacing.large) {
            VStack(alignment: .leading, spacing: NSPSpacing.medium) {
                MeetingStateBadge(state: meeting.lifecycleState)
                LabeledContent("Duration", value: durationLabel)
                LabeledContent("Availability", value: availabilityLabel)
                LabeledContent("Processing mode", value: meeting.processingMode.rawValue)
                LabeledContent("Started", value: meeting.startedAt.formatted(date: .abbreviated, time: .shortened))
            }
            .nspCard()

            if let executiveSummary {
                VStack(alignment: .leading, spacing: NSPSpacing.small) {
                    Text("Summary").font(Typo.ui(15, .bold))
                    Text(executiveSummary.text).font(Typo.ui(14, .medium))
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .nspCard()
            } else if meeting.lifecycleState == .partialFailure {
                EmptyTabPlaceholder(
                    title: "No summary generated", systemImage: "sparkles",
                    message:
                        "The transcript saved, but no summary or action items came back — usually because "
                        + "the on-device AI model isn't available on this device yet, or no clear commitments "
                        + "were found. Check the Transcript tab; the recording itself is unaffected.")
            } else {
                EmptyTabPlaceholder(
                    title: "No recap yet", systemImage: "sparkles",
                    message: "A flash recap and executive summary appear here once this meeting is processed.")
            }

            projectSection
            peopleSection
            deleteSection
        }
        .task {
            await loadExecutiveSummary()
            await loadAttendees()
            await loadProjects()
        }
        .sheet(isPresented: $isEditingAttendees) {
            AttendeesEditSheet(
                meetingID: meeting.meetingID, environment: environment, onDone: { Task { await loadAttendees() } })
        }
        .sheet(isPresented: $isEditingProject) {
            ProjectLinkEditSheet(meeting: meeting, environment: environment, onDone: { Task { await loadProjects() } })
        }
    }

    private var peopleSection: some View {
        VStack(alignment: .leading, spacing: NSPSpacing.medium) {
            HStack {
                Text("People").font(Typo.ui(15, .bold))
                Spacer()
                Button("Edit") { isEditingAttendees = true }.font(Typo.ui(11.5, .medium))
            }
            if attendees.isEmpty {
                Text("No attendees added yet.").font(Typo.ui(11.5, .medium)).foregroundStyle(Palette.textTertiary)
            } else {
                ForEach(attendees) { person in
                    Text(person.name).font(Typo.ui(14, .medium))
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .nspCard()
    }

    private var projectSection: some View {
        VStack(alignment: .leading, spacing: NSPSpacing.medium) {
            HStack {
                Text("Project").font(Typo.ui(15, .bold))
                Spacer()
                Button("Edit") { isEditingProject = true }.font(Typo.ui(11.5, .medium))
            }
            if linkedProjects.isEmpty {
                Text("Not linked to a project.").font(Typo.ui(11.5, .medium)).foregroundStyle(Palette.textTertiary)
            } else {
                ForEach(linkedProjects) { project in
                    Text(project.name).font(Typo.ui(14, .medium))
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .nspCard()
    }

    private var deleteSection: some View {
        VStack(alignment: .leading, spacing: NSPSpacing.small) {
            Button(role: .destructive) {
                isConfirmingDelete = true
            } label: {
                Label("Delete Recording", systemImage: "trash").frame(maxWidth: .infinity)
            }
            .buttonStyle(.bordered)
            .tint(Palette.danger.foreground)
            if let deleteError {
                Text(deleteError).font(Typo.ui(11.5, .medium)).foregroundStyle(Palette.danger.foreground)
            }
        }
        .confirmationDialog(
            "Delete this recording?", isPresented: $isConfirmingDelete, titleVisibility: .visible
        ) {
            Button("Delete Recording", role: .destructive) { Task { await deleteMeeting() } }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("Removes the recording, notes, transcript, and any linked action items. Can't be undone.")
        }
    }

    private func loadExecutiveSummary() async {
        let insights = try? await environment.insightRepository.fetchAll(meetingID: meeting.meetingID)
        executiveSummary = insights?.first { $0.layer == .executiveSummary }
    }

    private func loadProjects() async {
        guard let projectIDs = try? await environment.projectRepository.fetchProjectIDs(for: meeting.meetingID)
        else { return }
        let all = (try? await environment.projectRepository.fetchAll(workspaceID: meeting.workspaceID)) ?? []
        linkedProjects = all.filter { projectIDs.contains($0.projectID) }
    }

    /// `environment.deleteMeeting` sets `lastDeletedMeetingID`, which
    /// `MeetingDetailView`'s own `.onChange` already watches to dismiss —
    /// no separate callback needed here.
    private func deleteMeeting() async {
        do {
            try await environment.deleteMeeting(meeting.meetingID)
        } catch {
            deleteError = "\(error)"
        }
    }

    private func loadAttendees() async {
        guard
            let attendeeIDs = try? await environment.meetingAttendeeRepository.fetchAttendeeIDs(
                for: meeting.meetingID)
        else { return }
        var people: [Person] = []
        for personID in attendeeIDs {
            if let person = try? await environment.personRepository.find(personID) {
                people.append(person)
            }
        }
        attendees = people.sorted { $0.name < $1.name }
    }
}

/// Toggles which people attended this meeting — following
/// `ThreadLinksEditSheet`'s exact "edit the whole set, save once" shape.
private struct AttendeesEditSheet: View {
    let meetingID: MeetingID
    let environment: AppEnvironment
    let onDone: () -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var allPeople: [Person] = []
    @State private var selectedPersonIDs: Set<PersonID> = []
    @State private var newPersonName = ""
    @State private var isSaving = false
    @State private var saveError: String?

    var body: some View {
        NavigationStack {
            Form {
                Section("Attendees") {
                    if allPeople.isEmpty {
                        Text("No people yet — add one below.").font(Typo.ui(11.5, .medium)).foregroundStyle(
                            Palette.textTertiary)
                    } else {
                        ForEach(allPeople) { person in
                            Toggle(person.name, isOn: binding(for: person.personID))
                        }
                    }
                }
                Section("Add Someone New") {
                    HStack {
                        TextField("Name", text: $newPersonName)
                        Button("Add") { Task { await addPerson() } }
                            .disabled(newPersonName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                    }
                }
                if let saveError {
                    Text(saveError).font(Typo.ui(11.5, .medium)).foregroundStyle(Palette.danger.foreground)
                }
            }
            .navigationTitle("Attendees")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") { Task { await save() } }.disabled(isSaving)
                }
            }
            .task { await load() }
        }
    }

    private func binding(for personID: PersonID) -> Binding<Bool> {
        Binding(
            get: { selectedPersonIDs.contains(personID) },
            set: { isOn in
                if isOn { selectedPersonIDs.insert(personID) } else { selectedPersonIDs.remove(personID) }
            })
    }

    private func load() async {
        guard let workspaceID = environment.defaultPolicy?.workspaceID else { return }
        let fetched = (try? await environment.personRepository.fetchAll(workspaceID: workspaceID)) ?? []
        allPeople = fetched.filter { $0.personID != environment.selfPersonID }
        selectedPersonIDs = (try? await environment.meetingAttendeeRepository.fetchAttendeeIDs(for: meetingID)) ?? []
    }

    private func addPerson() async {
        guard let workspaceID = environment.defaultPolicy?.workspaceID else { return }
        let trimmed = newPersonName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        let person = Person(personID: PersonID(rawValue: UUID()), workspaceID: workspaceID, name: trimmed)
        do {
            try await environment.personRepository.insert(person, at: environment.clock.now())
            allPeople.append(person)
            selectedPersonIDs.insert(person.personID)
            newPersonName = ""
        } catch {
            saveError = "\(error)"
        }
    }

    private func save() async {
        isSaving = true
        defer { isSaving = false }
        do {
            try await environment.meetingAttendeeRepository.setAttendees(
                for: meetingID, personIDs: selectedPersonIDs)
            onDone()
            dismiss()
        } catch {
            saveError = "\(error)"
        }
    }
}

/// Sets this meeting's project link — single-select, since a `Meeting`
/// joins at most one project (`Project`'s own doc comment); a Brain Dump's
/// own relationship to several projects at once is a separate future UI,
/// not this sheet.
private struct ProjectLinkEditSheet: View {
    let meeting: Meeting
    let environment: AppEnvironment
    let onDone: () -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var projects: [Project] = []
    @State private var selectedProjectIDs: Set<ProjectID> = []
    @State private var isSaving = false
    @State private var saveError: String?

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    if projects.isEmpty {
                        Text("No projects yet — create one from the Projects tab.")
                            .font(Typo.ui(11.5, .medium))
                            .foregroundStyle(Palette.textTertiary)
                    } else {
                        Picker(
                            "Project",
                            selection: Binding(
                                get: { selectedProjectIDs.first },
                                set: { selectedProjectIDs = $0.map { [$0] } ?? [] })
                        ) {
                            Text("None").tag(ProjectID?.none)
                            ForEach(projects) { project in
                                Text(project.name).tag(ProjectID?.some(project.projectID))
                            }
                        }
                    }
                }
                if let saveError {
                    Text(saveError).font(Typo.ui(11.5, .medium)).foregroundStyle(Palette.danger.foreground)
                }
            }
            .navigationTitle("Project")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") { Task { await save() } }.disabled(isSaving)
                }
            }
            .task { await load() }
        }
    }

    private func load() async {
        projects = (try? await environment.projectRepository.fetchAll(workspaceID: meeting.workspaceID)) ?? []
        selectedProjectIDs =
            (try? await environment.projectRepository.fetchProjectIDs(for: meeting.meetingID)) ?? []
    }

    private func save() async {
        isSaving = true
        defer { isSaving = false }
        do {
            try await environment.projectRepository.setProjects(
                for: meeting.meetingID, projectIDs: selectedProjectIDs)
            onDone()
            dismiss()
        } catch {
            saveError = "\(error)"
        }
    }
}
